name: hive_wait
description: Wait until the Hive is ready to use before calling the box's methods.
version: 1.0.2+1
homepage: https://github.com/joutvhu/hive_wait

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.1.0
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
