name: hiverepo
description: Hive repository
version: 1.0.0
homepage: https://github.com/joutvhu/hiverepo

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  hive: ^2.1.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
