name: hiverepo
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/joutvhu/hiverepo

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  hive: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
